# site settings
title: faze-geek
subtitle: by HTML5 UP
email: anuragbhatgsoc23@gmail.com
description: Open Source
baseurl: "" # the subpath of your site, e.g. /blog
url: faze-geek.github.io
author: Anurag
street_address:
city: Mumbai
state: Maharashtra
zip_code:
country: India
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/faze-geek
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/anurag-bhat-7b4189228/
pinterest_url:
slack_url:
twitter_url:
gmail_url: bhat.1@iitj.ac.in

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-feed
